sql_test_assignment:
  target: clickhouse
  outputs:
    clickhouse:
      type: clickhouse
      schema: default
      user: default
      #password: [default]
      #optional fields
      driver: http
      port: 18123
      host: localhost
      retries: 1
      verify: False
      secure: False
      connect_timeout: 10
      send_receive_timeout: 300
      sync_request_timeout: 5
      #compression: False
      compress_block_size: 1048576
      #database_engine: <db_engine>
      check_exchange: True
      #use_lw_deletes: False
      #custom_settings: <empty>